import express from "express";
import { RegisterRoutes } from "./routes/routes"; // Auto-generated by tsoa
import swaggerUi from "swagger-ui-express";
import fs from "fs";
import yaml from "yaml";
import cors from "cors";

const app = express();
app.use(express.json());
app.use(cors());

const swaggerDocument = JSON.parse(fs.readFileSync("./src/swagger.json", "utf8"));
console.log(swaggerDocument.servers)
// Serve Swagger UI
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Register TSOA Routes
RegisterRoutes(app);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));
